### ISSUE TITLE
marshal errors in logs, unable to load config file

### ISSUE THREAD

**Issue by prageethw** [vfarcic/docker-flow-monitor#15]
**steps to reproduce:**

1. check out the code https://github.com/vfarcic/docker-flow-monitor.
2. uncomment below section in stacks/docker-flow-monitor-proxy.yml
----
 #- com.df.serviceName=monitor
 #- com.df.scrapeType=static_configs
 #- com.df.scrapePort=9090
----
3. run the ./scripts/dm-swarm-04.sh
4. determine monitor container id and get the log.
5. try to access  dfm using open "http://$(docker-machine ip swarm-1)/monitor/config"

**exected:**
there should not be any log errors

**actual:**
marshal errors in logs,  trying to process "/etc/prometheus/prometheus.yml". this  stops integration between  dfp and dfm.

can  not access the endpoint, "Docker Flow Proxy: 503 Service Unavailable"

**logs:**

2017/11/08 01:47:17 /bin/sh -c prometheus -web.external-url="http://192.168.99.100/monitor" -web.route-prefix="/monitor" -config.file="/etc/prometheus/prometheus.yml" -storage.local.path="/prometheus" -web.console.libraries="/usr/share/prometheus/console_libraries" -web.console.templates="/usr/share/prometheus/consoles"
time="2017-11-08T01:47:17Z" level=info msg="Starting prometheus (version=1.8.1, branch=HEAD, revision=3a7c51ab70fc7615cd318204d3aa7c078b7c5b20)" source="main.go:87"
time="2017-11-08T01:47:17Z" level=info msg="Build context (go=go1.9.1, user=root@ab78fb101775, date=20171023-15:50:57)" source="main.go:88"
time="2017-11-08T01:47:17Z" level=info msg="Host details (Linux 4.4.93-boot2docker #1 SMP Wed Oct 18 17:00:16 UTC 2017 x86_64 923dc40e55ff (none))" source="main.go:89"
time="2017-11-08T01:47:17Z" level=info msg="Loading configuration file /etc/prometheus/prometheus.yml" source="main.go:254"
time="2017-11-08T01:47:17Z" level=error msg="Error loading config: couldn't load configuration (-config.file=/etc/prometheus/prometheus.yml): yaml: unmarshal errors:
  line 10: cannot unmarshal !!seq into string" source="main.go:160"
2017/11/08 01:47:21 Processing /v1/docker-flow-monitor/reconfigure?distribute=true&port=9090&replicas=1&scrapePort=9090&scrapeType=static_configs&serviceDomain=192.168.99.100&serviceName=monitor&servicePath=%!F(MISSING)monitor

**Comment by vfarcic** [comment]
This should be fixed with the PR #14. Can you please give it another round of testing to confirm that the merge was successful? The image is `vfarcic/docker-flow-monitor:17.11.11-25`.

**Comment by prageethw** [comment]
nope container fails  when I uncomment 

below 
#- com.df.serviceName=monitor
#- com.df.scrapeType=static_configs
#- com.df.scrapePort=9090

logs:
2017/11/12 11:46:13 Requesting services from Docker Flow Swarm Listener
2017/11/12 11:46:13 Processing: [{"distribute":"true","port":"9090","replicas":"1","scrapePort":"9090","scrapeType":"static_configs","serviceDomain":"192.168.99.100","serviceName":"monitor","servicePath":"/monitor"}]
GLOBAL_SCRAPE_INTERVAL=10s
2017/11/12 11:46:13 Writing to prometheus.yml
2017/11/12 11:46:13 Starting Docker Flow Monitor
2017/11/12 11:46:13 Starting Prometheus
ARG_WEB_EXTERNAL-URL=http://192.168.99.100/monitor
ARG_WEB_ROUTE-PREFIX=/monitor
ARG_CONFIG_FILE=/etc/prometheus/prometheus.yml
ARG_STORAGE_LOCAL_PATH=/prometheus
ARG_WEB_CONSOLE_LIBRARIES=/usr/share/prometheus/console_libraries
ARG_WEB_CONSOLE_TEMPLATES=/usr/share/prometheus/consoles
2017/11/12 11:46:13 /bin/sh -c prometheus -web.external-url="http://192.168.99.100/monitor" -web.route-prefix="/monitor" -config.file="/etc/prometheus/prometheus.yml" -storage.local.path="/prometheus" -web.console.libraries="/usr/share/prometheus/console_libraries" -web.console.templates="/usr/share/prometheus/consoles"
time="2017-11-12T11:46:13Z" level=info msg="Starting prometheus (version=1.8.1, branch=HEAD, revision=3a7c51ab70fc7615cd318204d3aa7c078b7c5b20)" source="main.go:87"
time="2017-11-12T11:46:13Z" level=info msg="Build context (go=go1.9.1, user=root@ab78fb101775, date=20171023-15:50:57)" source="main.go:88"
time="2017-11-12T11:46:13Z" level=info msg="Host details (Linux 4.4.93-boot2docker #1 SMP Wed Oct 18 17:00:16 UTC 2017 x86_64 0461f0e56ddd (none))" source="main.go:89"
time="2017-11-12T11:46:13Z" level=info msg="Loading configuration file /etc/prometheus/prometheus.yml" source="main.go:254"
time="2017-11-12T11:46:13Z" level=error msg="Error loading config: couldn't load configuration (-config.file=/etc/prometheus/prometheus.yml): yaml: unmarshal errors:
  line 10: cannot unmarshal !!seq into string" source="main.go:160"


terminal:

ID                  NAME                       IMAGE                                       NODE                DESIRED STATE       CURRENT STATE                ERROR                              PORTS
veq2uz64pfjk        monitor_monitor.1          vfarcic/docker-flow-monitor:17.11.11-25     swarm-1             Running             Starting 1 second ago
c1yjui7m0yk1         \_ monitor_monitor.1      vfarcic/docker-flow-monitor:17.11.11-25     swarm-1             Shutdown            Failed 6 seconds ago         "task: non-zero exit (2): dock…"
mdqqsr3vrytf         \_ monitor_monitor.1      vfarcic/docker-flow-monitor:17.11.11-25     swarm-1             Shutdown            Failed 29 seconds ago        "task: non-zero exit (2): dock…"
e6yv27phyy7g         \_ monitor_monitor.1      vfarcic/docker-flow-monitor:17.11.11-25     swarm-3             Shutdown            Failed 52 seconds ago        "task: non-zero exit (2): dock…"
e81trzxnqzmn         \_ monitor_monitor.1      vfarcic/docker-flow-monitor:17.11.11-25     swarm-1             Shutdown            Failed about a minute ago    "task: non-zero exit (2): dock…"
vawhutkpeb9f        monitor_swarm-listener.1   vfarcic/docker-flow-swarm-listener:latest   swarm-2             Running             Running about a minute ago

**Comment by prageethw** [comment]
please close this issue...
