### ISSUE TITLE
Allow sub-value options in GLOBAL configurations

### ISSUE THREAD

**Issue by joskfg** [vfarcic/docker-flow-monitor#2]
Currently (v0.32), df-monitor allow you to define environment variables that create the prometheus.yml. The variables should be names like `GLOBAL_SCRAPE_INTERVAL=10s` and they are transformed to:
```
global:
  scapre_interval: 10s
```

The issue is about sub values inside global, for example:
```
global:
  labels:
    cluster: swarm
```

This is not possible to reproduce because `GLOBAL_LABELS_CLUSTER=swam` creates:
```
global:
  labels_cluster: swarm
```
instead of the expected.

A possible solution is to use `-` for sub-values. Something like: `GLOBAL-LABELS-CLUSTER=swarm`.

Thanks!

**Comment by vfarcic** [comment]
It's implemented in the [release 0.38](https://github.com/vfarcic/docker-flow-monitor/releases/tag/0.38). Can you please try it out and let me know if it works as expected.
