### ISSUE TITLE
docker-flow-monitor-aws.yml not starts properly

### ISSUE THREAD

**Issue by redtex** [vfarcic/docker-flow-monitor#26]
Stack https://raw.githubusercontent.com/vfarcic/docker-flow-monitor/master/stacks/docker-flow-monitor-aws.yml not starts properly. Namely monitor service, because of permission denied in /data directory - it has 755 root:root security settings, but docker-flow-monitor runs from 'nobody' user. To start stack properly I had to change:

```
    environment:
-      - ARG_STORAGE_LOCAL_PATH=/data

    volumes:
-      - prom:/data
+      - prom:/prometheus
```

**Comment by vfarcic** [comment]
I forgot to update that file since switching to Prometheus 2. The changes you did are correct. I updated the repo's YAML file.
