### ISSUE TITLE
Image prom/alertmanager using new rule format

### ISSUE THREAD

**Issue by fgendc** [vfarcic/docker-flow-monitor#27]
Thanks for sharing, vfarcic!

Checked running docker-flow-monitor-slack-9093.yml that the latest image prom/alertmanager has changed the rule format according to [this post](https://prometheus.io/blog/2017/06/21/prometheus-20-alpha3-new-rule-format/) from using single dash (-config.file) to double dash (--config.file)

**Comment by vfarcic** [comment]
Are you referring to `monitor` or `alert-manager` service from https://github.com/vfarcic/docker-flow-monitor/blob/master/stacks/docker-flow-monitor-slack-9093.yml ? Only the latter (`alert-manager`) uses `-config.file` and it's syntax didn't change (as far as I know).

I probably misunderstood the issue...

**Comment by fgendc** [comment]
Sorry, it’s the command tag in alert-manager. Didn’t work with single dash while I was following devops 2.2, switched it to double dash and it did work

**Comment by vfarcic** [comment]
You're right. Alertmanager arguments changed and I missed updating the stacks. They should be OK now. Can you please try it out and let me know whether it works as expected?

**Comment by fgendc** [comment]
Works like a charm now. Thanks man!
