### ISSUE TITLE
Optional Docker Secret for alert shortcuts

### ISSUE THREAD

**Issue by dave08** [vfarcic/docker-flow-monitor#28]
Like as a YAML file. It should probably have some kind of naming convention (like cert-* in DFP).

**Comment by vfarcic** [comment]
@dave08 I made the changes required for the basic functionality. However, I did not have time to test it properly. Can you give me a hand and do the following?

1. Update DFM to the tag `vfarcic/docker-flow-monitor:issue-28`.
2. Test that the old functionality works properly.
3. Replace `/etc/dfm/shortcuts.yaml` with Docker config or secret and confirm that it works.

If all three points work, we can continue by extending the functionality and writing docs.

**Comment by dave08** [comment]
Sure, I'll get to it tomorrow when I get to work, thanks!

**Comment by dave08** [comment]
I tried updating today, but dfp just keeps on failing because of rexray problems... I guess I'll try again tomorrow... thanks again for all your efforts!

**Comment by vfarcic** [comment]
We recently switched to Prometheus 2.x. The data needs to be migrated (or discarded). You can find the info in http://monitor.dockerflow.com/migration/ . Also, the user inside the container changed to `nobody` as well as the default data directory. Now it's `/prometheus`. You can see an updated example with the volume in https://github.com/vfarcic/docker-flow-monitor/blob/master/stacks/docker-flow-monitor-aws.yml .

Please let me know if that helps.

**Comment by dave08** [comment]
I was already at 2.x and I did the migration... Just RexRay that's not able to get the DO block storage volume back up... These are the times I wish I were using cloudstor...

**Comment by dave08** [comment]
Ok, it finally came up... and the configs seem fine, I just have to find the time in the next few days to test the rest. I'm afraid to do it now, since it took a while to get it working again with all the Rexray volume problems...

**Comment by vfarcic** [comment]
Can we close this issue or the problem still persists?

**Comment by dave08** [comment]
My Prometheus is still down because of Rexray driver problems, next week we should be making decisions about that. If I could get Prometheus running normally, I could check out what happens when the file is replaced and get to the docs... This is really a nice feature since we'll need a bunch of custom shortcuts...

**Comment by vfarcic** [comment]
You can make Prometheus run without volumes if you need only to check something.

**Comment by vfarcic** [comment]
It's available in the [release 2-18.02.17-51](https://github.com/vfarcic/docker-flow-monitor/releases/tag/2-18.02.17-51).

**Comment by dave08** [comment]
Thanks alot! I'm sorry I didn't have a chance to test this further... I put up prometheus w/o a rexray volume, bit I was really swamped with work...
