### ISSUE TITLE
DFM config changes from file_sd_configs to dns_sd_configs

### ISSUE THREAD

**Issue by dsw9742** [vfarcic/docker-flow-monitor#38]
Using the flexible labeling feature of DFM, we are experiencing an issue where DFM initially creates a Prometheus job using the `file_sd_configs` options for services, but then changes to using the `dns_sd_configs` options for services. This results in all flexible labels being dropped from the scraped data -- we are left with only `instance` and `job` target labels.

It seems that this change occurs when DFM is updated with `docker service update` -- we are adding a new network to DFM with the `--network-add` flag. I feel I should also point out that our DFM is connected to at least 8 different overlay networks (we isolate our services as much as possible), so that multiple networks may not be a highly-utilized or tested scenario at present but I think is a feasible one from a design standpoint.

**Comment by dsw9742** [comment]
I am continuing to investigate this issue on my end. 

Digging deeper into our logs, it looks as though `dns_sd_config` is chosen for a service job if the `reconfigure` request to DFM from DFSL does not contain the `nodeInfo` parameter.

What is mystifying to me is why some of our services result in `reconfigure` requests containing `nodeInfo` and some do not, when the services use nearly identical definitions.

I can provide plenty of supporting material if that would help -- excerpts of logs from DFM and DFSL, service definitions, the resulting prometheus.yml config file from DFM.

But I am at a complete loss as to why this is occurring and could really use any assistance.

**Comment by dsw9742** [comment]
I believe this is related to an Alpine issue. Prometheus uses Alpine/Busybox base. https://github.com/gliderlabs/docker-alpine/issues/313

**Comment by thomasjpfan** [comment]
@dsw9742 Without the `nodeInfo` parameter, DFM will default to using `dns_sd_config`. DFSL uses dockers api with `com.df.scapeNetwork` to look up the addresses for a service. If DFSL is not picking up the address, it could mean the docker has no assigned an IP to the service yet. 🤔

Is `com.df.scrapeNetwork` set for each service and `DF_INCLUDE_IP_INFO` set to true in DFSL?

**Comment by thomasjpfan** [comment]
I was able to reproduce this issue, docker needs a little time to assign a service an ip corresponding to a overlay network. If DFSL queries for the ip too quickly, it would not find the node information at that moment in time.

**Comment by dsw9742** [comment]
@thomasjpfan that makes total sense based on some of my observations -- several of the services that "flip" take a long time to start up.

I've continued to look into this on my end as well and I'm beginning to think I am dealing with multiple issues, but it would be great to be able to check off one of them!

**Comment by thomasjpfan** [comment]
DFSL now waits for tasks to converge before sending out notifications. This feature is available starting from [release 18.03.13-35](https://github.com/vfarcic/docker-flow-swarm-listener/releases/tag/18.03.13-35).

**Comment by dsw9742** [comment]
@thomasjpfan I've pulled the latest and am seeing if the updates improve our scenario.

**Comment by dsw9742** [comment]
Some additional updates.

It seems we've stumbling across documented DNS issues with the combination of Virtualbox (used by us in dev environments), musl (used in Alpine), and AAAA records (used by DNS for IP6). Reference https://bugs.alpinelinux.org/issues/6221 and also http://www.openwall.com/lists/musl/2017/09/28/1. I encountered 5s timeouts with DNS very regularly during investigations, so if this isn't root cause, I still feel it is very likely related. Note these issues appear to occur whether or not Docker is part of the tech stack in use.

We *think* what is happening is that the DNS problems are encountering enough hangups to substantially affect the Docker Swarm stack, particularly any services dependent on musl. In many cases these problems also affect service healthchecks, to the degree they prevent the service from ever starting up and remaining in a running state.*

The short-term fix was to remove healthchecks (`--no-healthcheck`) and set a very short timeout for DNS (`--dns-option=timeout:1`) on the affected services. I don't know if this is comprehensive or what other side-effects we might incur because of it, but it allows _most_ everything to function as expected (saw DFSL -- the first service we start -- default to `dns_sd_configs` this morning rather than `file_sd_configs`, I am guessing due to the aggressive DNS timeout).

The long-term fix for us is probably to disable all host-DNS-related settings in Virtualbox and introduce a DNS service within the Swarm stack. We'll configure Swarm services to use the DNS service. To date, we have been using the `/etc/hosts` file on the Virtualbox hosts to develop against test domains, but if we can no longer do that, we will need to pull them from inside the Swarm -- hence the need for a DNS service. Given the nuances of DNS with musl (reference https://wiki.musl-libc.org/functional-differences-from-glibc.html#Name-Resolver/DNS), this may have additional performance benefits for glibc-based services if the internal DNS service is their primary DNS provider.

What can be done in the docker flow stack? I think an option to "force" the service discovery type would be ideal. It looks like the right API options are in place for DFM (see `scrapeType` at http://monitor.dockerflow.com/usage/#scrape-parameters), but it's not clear to me if values for that parameter can be set (i.e. "forced") on the target services. I don't see anything in the documentation but I could certainly have missed something. Does anyone know?

I can't imagine we're the only ones to encounter this problem, so if there are other workarounds, warnings, or considerations, I would love to hear them. Any and all feedback is welcome. Documenting some of this besides in the DFM issue-tracker might also be helpful, though I'm not immediately sure where we should do that or what form it should take.

* I twiddled with every healthcheck-related setting I could think of, but even using long values like 60s for timeout didn't allow the service to remain in a running state. The only thing that worked was adding the `--no-healthcheck` when creating the service, and then updating the service to reenable healthchecks after startup.

**Comment by thomasjpfan** [comment]
After the DNS issues are resolved, you can force DFSL to send out service notifications again to DFM by sending a GET request to DFSL: http://swarmlistener.dockerflow.com/usage/#notify-services. The endpoint is `/v1/docker-flow-swarm-listener/notify-services`.

**Comment by dsw9742** [comment]
Thanks @thomasjpfan, that sounds like a solid recovery mechanism. Assuming that there's not currently a way to set the required scrapeType data through targeted service labels then? I'm trying to think where I could inspect the requests that pass that parameter. ..

**Comment by thomasjpfan** [comment]
DFSL does not pass the `scrapeType` parameter to DFM. DFSL passes the node and ip information of each target and sends it to DFM. If DFM sees this information, it will construct the `file_sd_config` needed for the targets. If DFM does not see the ip info, it defaults to `dns_sd_config`.

In your situation, there should be a service watching when the DNS issue is resolved, and send a `notify-services` request to DFSL to send the ip info to DFM.

**Comment by dsw9742** [comment]
@thomasjpfan ah, OK, so DFM does not evaluate the `com.df.scrapeType` label if it receives a request containing node and ip information from DFSL?

**Comment by thomasjpfan** [comment]
That is correct.

**Comment by vfarcic** [comment]
Can we close this issue?

**Comment by dsw9742** [comment]
Yes
