### ISSUE TITLE
Passing engine or node labels to Prometheus

### ISSUE THREAD

**Issue by dsw9742** [vfarcic/docker-flow-monitor#42]
Service labels are useful but we have to use labels at the engine or node level to add metadata about environment and  infrastructure, e.g. cloud provider, region, availability zone, instance, etc., which is pretty useful information in monitoring data.

Is there a mechanism or technique by which we can pass engine or node labels to Prometheus with DFM?

**Comment by dave08** [comment]
I was also thinking the same thing! Currently what would have to be done is to split the service into many services and use placement contstraints together w/ flexible labeling, which is bit of a waste... but for what you're requesting DFSL would also have to send node and engine labels to DFM...?

**Comment by dsw9742** [comment]
@dave08 not sure I understand it all well enough to answer requirements though you could be right. I think I saw a recent update to Docker Swarm that enables use of engine labels with service environment variables templating -- I don't think templating works with labels but maybe the same technique

**Comment by dsw9742** [comment]
could be applied in DFM for this feature request?

**Comment by dsw9742** [comment]
Here's the SwarmKit pull request for the templating with engine labels feature I referenced https://github.com/docker/swarmkit/pull/2372.

**Comment by dsw9742** [comment]
It appears as though container labels contain a reference to the node ID (`Config.Labels` contains `com.docker.swarm.node.id`), which could in theory be used to retrieve both node (`Spec.Labels`) and engine (`Description.Engine.Labels`) labels and apply them to the file_sd when it is created or updated.

**Comment by dsw9742** [comment]
@thomasjpfan I think you might be the best person to ask about this scenario. If it isn't currently possible, but the idea has merit, I'd be happy to write up a formal feature request.

**Comment by thomasjpfan** [comment]
This is a good idea. DFSL would have to be updated to add additional label information.

**Comment by thomasjpfan** [comment]
I will work on this by taking advantage of the new node events API of DFSL.

**Comment by thomasjpfan** [comment]
Till #44 is merged, you can try out this feature out by pulling `thomasjpfan/docker-flow-monitor:aeacdf59`. I have updated the flexible label tutorial here: https://github.com/thomasjpfan/docker-flow-monitor/blob/nodeID-rb/docs/tutorial-flexible-labeling.md.

The updated stack needed to run the tutorial is at [stacks/docker-flow-monitor-flexible-labels.yml](https://github.com/thomasjpfan/docker-flow-monitor/blob/nodeID-rb/stacks/docker-flow-monitor-flexible-labels.yml).

**Comment by thomasjpfan** [comment]
This feature is implemented in DFM with tag `2-18.03.26-58` or later. For information on how to use this feature visit: http://monitor.dockerflow.com/tutorial-flexible-labeling/.

**Comment by vfarcic** [comment]
Can we close this issue?

**Comment by dsw9742** [comment]
Looks good to go from my end. Great stuff, thanks guys!
