### ISSUE TITLE
Alternative to AlertIf @service_mem_limit shortcut

### ISSUE THREAD

**Issue by redtex** [vfarcic/docker-flow-monitor#43]
The `@service_mem_limit `shortcut uses as base an `container_memory_usage_bytes` metric, which includes application memory and linux page cache. Such metric good for those kind of applications, which has low disk activity, such as web services and so on... But in case of databases or file servers and other applications with moderate to high disk activity, this shortcut will always tend to 1, because of nature of Linux disk page cache, which try to use all available memory. So, my suggestion is to make new shortcut, which will substract value of `container_memory_cache`  from `container_memory_usage_bytes` for it's base. 
Example: If `serviceName` is set to `my-service`, `@service_mem_limit_nobuff:0.8` would be expanded to `(container_memory_usage_bytes{container_label_com_docker_swarm_service_name="my-service"}-container_memory_cache{container_label_com_docker_swarm_service_name="my-service"})/container_spec_memory_limit_bytes{container_label_com_docker_swarm_service_name="my-service"} > 0.8.`

**Comment by vfarcic** [comment]
@redtex Can you make a PR with the new shortcut? You'd only need to change https://github.com/vfarcic/docker-flow-monitor/blob/master/conf/shortcuts.yaml, one more test entry to https://github.com/vfarcic/docker-flow-monitor/blob/master/server/server_test.go#L285, and modify docs in https://github.com/vfarcic/docker-flow-monitor/blob/master/docs/usage.md.

**Comment by redtex** [comment]
@vfarcic Victor, thank you.
