### ISSUE TITLE
feature request: support multiple alert manager services via ARG_ALERTMANAGER_URL env var

### ISSUE THREAD

**Issue by dsw9742** [vfarcic/docker-flow-monitor#46]
According to [official Alertmanager documentation](https://prometheus.io/docs/alerting/alertmanager/), 

> It's important not to load balance traffic between Prometheus and its Alertmanagers, but instead, point Prometheus to a list of all Alertmanagers.

DFM, at present, appears to only support a single URL for Alertmanager via the `ARG_ALERTMANAGER_URL` environment variable.

This is a feature request to support multiple Alertmanager URLs. There are several instances of DF services that support similar mechanisms, either with indexes or comma-separation. Would it be possible to implement a similar mechanism to enable support of this feature in DFM?

**Comment by thomasjpfan** [comment]
All the prometheus config options can be access through env variables. For example it is possible to get this prometheus configuration:

```yaml
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alert-manager:9093
      - alert-manager2:9093
    scheme: http
```

with the following environmental variables:

```
ALERTING__ALERTMANAGERS_1__STATIC_CONFIGS_1__TARGETS_1=alert-manager:9093
ALERTING__ALERTMANAGERS_1__STATIC_CONFIGS_1__TARGETS_2=alert-manager2:9093
ALERTING__ALERTMANAGERS_1__SCHEME=http
```

This can be quite verbose, so I extended `ARG_ALERTMANAGER_URL` to accept comma seperated urls. Thus `ARG_ALERTMANAGER_URL=http://alert-manager:9093,http://alert-manager2:9093` will result in the same yaml configuration. This feature can be used starting from `2-18.05.16-3`.

**Comment by dsw9742** [comment]
@thomasjpfan will test this this morning

**Comment by dsw9742** [comment]
@thomasjpfan looks like this works, at least based on Prometheus configuration displayed in the UI. Will file a separate issue if problems turn up but I think this is good to go!
