### ISSUE TITLE
typo in 'replicas_more_than' shortcut

### ISSUE THREAD

**Issue by dsw9742** [vfarcic/docker-flow-monitor#52]
<pre>
"@replicas_more_than":
  expanded: count(container_memory_usage_bytes{container_label_com_docker_swarm_service_name="{{ .Alert.ServiceName }}"}) > {{ .Alert.Replicas }}
  annotations:
    summary: The number of running replicas of the service {{ .Alert.ServiceName }} is more than {{ .Alert.Replicas }}
  labels:
    receiver: system
    service: "{{ .Alert.ServiceName }}"
    scale: <b>up</b>
    type: node
</pre>

Shouldn't the scale value should be `down` rather than `up` for this shortcut? Seems odd for the same scale value to be in place for both `replicas_less_than` and `replicas_more_than` shortcuts.

**Comment by vfarcic** [comment]
Fixed and available in `18.05.26-4`
