### ISSUE TITLE
Source prometheus.yml

### ISSUE THREAD

**Issue by Blaiserman** [vfarcic/docker-flow-monitor#6]
Hi
Where can I find your prometheus.yml or how can I add rule_files to your prometheus??
THX

**Comment by vfarcic** [comment]
The idea behind the project is to configure Prometheus with each service deployed to a cluster, as an alternative to defining static config. Rules are created through labels described in http://monitor.dockerflow.com/usage/#alert-parameters. I'd suggest going through the [Running Docker Flow Monitor](http://monitor.dockerflow.com/tutorial/) and [Auto-Scaling Docker Swarm Services Using Instrumented Metrics](http://monitor.dockerflow.com/auto-scaling/) tutorials to get general idea behind the project.

Please let me know if those pages resolve your doubts.

**Comment by vfarcic** [comment]
Closing this issue since it became inactive. Please reopen it if you'd like to continue the conversation.
