### ISSUE TITLE
additional configurations

### ISSUE THREAD

**Issue by vicjeancar** [vfarcic/docker-flow-monitor#8]
i want to use this 2 configurations in your image

remote_write:
    - url: "http://prometheus_postgresql_adapter:9201/write"
remote_read:
    - url: "http://prometheus_postgresql_adapter:9201/read"
how can i do it by environment flags in a compose file

**Comment by vfarcic** [comment]
Can you please let me know which exporter you're using? Is it https://github.com/wrouesnel/postgres_exporter?

**Comment by vfarcic** [comment]
It's available from the [release 17.10.03-18](https://github.com/vfarcic/docker-flow-monitor/releases/tag/17.10.03-18).
