### ISSUE TITLE
Specifying command-line argument with ARG_ fails for values containing "="

### ISSUE THREAD

**Issue by podloucky-init** [vfarcic/docker-flow-monitor#9]
Hi there,

Took a look at docker-flow-monitor recently and ran into the following problem:
If a value contains an "=" the command-line argument is truncated.
Example:
`ARG_LOG_FORMAT="logger:stdout?json=true"`
results in:
`-log.format="logger:stdout?json`

Clearly, the issue originates in `prometheus/util.go:getArgFromEnv()`: Environment variables in the form `NAME=VALUE` are split at "=" and only the first two parts are considered.

Thanks in advance for a fix!

**Comment by vfarcic** [comment]
It's fixed in the release `17.10.04-19`. Can you please try it out and let me know if it works as expected?

**Comment by podloucky-init** [comment]
Works perfectly! Thanks for the quick fix, this is much appreciated.
